changelog:
  change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
  categories:
    - title: Highlights
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - regression
    - title: Docs and DX
      labels:
        - docs
        - dx
  exclude:
    labels:
      - skip-release-notes
      - ci
      - chore
