import {
  ArrowUpCircle,
  BarChart3,
  BookOpen,
  BookOpenText,
  BookText,
  Bot,
  Brain,
  Boxes,
  Box,
  FileText,
  HardDrive,
  LayoutDashboard,
  type LucideIcon,
  MessageCircle,
  MessageSquare,
  MoonStar,
  Network,
  Plug,
  Radio,
  ScrollText,
  Settings2,
  Shell,
  Sparkles,
  Users,
  Wrench,
  Zap,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  'bar-chart-3': BarChart3,
  brain: Brain,
  radio: Radio,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  box: Box,
  boxes: Boxes,
  zap: Zap,
  users: Users,
  'settings-2': Settings2,
  'file-text': FileText,
  'book-text': BookText,
  'book-open': BookOpen,
  'book-open-text': BookOpenText,
  'scroll-text': ScrollText,
  wrench: Wrench,
  plug: Plug,
  shell: Shell,
  'hard-drive': HardDrive,
  network: Network,
  sparkles: Sparkles,
  'moon-star': MoonStar,
  'arrow-up-circle': ArrowUpCircle,
  bot: Bot,
}

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Box
}
